#!/usr/bin/env python3
from http.server import BaseHTTPRequestHandler, HTTPServer
import json
import sys

端口 = int(sys.argv[sys.argv.index("--port") + 1])

class 处理器(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/v1/models":
            数据 = json.dumps({"object": "list", "data": []}).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(数据)))
            self.end_headers()
            self.wfile.write(数据)
        else:
            self.send_response(404)
            self.end_headers()
    def log_message(self, *_):
        pass

HTTPServer(("127.0.0.1", 端口), 处理器).serve_forever()
